{% set name = "bioviz" %}
{% set version = "2.4.1" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: fa77c36cca45254544fe55d02ca86f6564397b74f8e4e4b81caab0472bd182c5

build:
  number: {{ build_num }}
  string: py{{ py }}_h{{ PKG_HASH }}_{{ build_num }}
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python
    - biorbd
    - vtk
    - pyqt
    - pyomeca
    - packaging

test:
  imports:
    - biorbd  # [linux]
    - bioviz  # [not linux and not arm64]

about:
  home: http://github.com/pyomeca/bioviz
  license: Apache-2.0
  license_file: LICENSE
  summary: Visualization toolkit for the biorbd suite
  description: |
    Biorbd visualization toolkit 
  doc_url: https://github.com/{{ name }}/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - pariterre
