{% set name = "biorbd-viz" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 3f91fca9b1d60bcd02b11be58e5850d2c177e816a9281a62a02990f62de076a7
  
build:
  skip: True  # [py<35]
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('biorbd') }}
    - vtk
    - pyqt
    - pyomeca

test:
  imports:
    - BiorbdViz  # [not linux]

about:
  home: http://github.com/pyomeca/biorbd-viz
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Biorbd visualization toolkit'
  description: |
    Biorbd visualization toolkit 
  doc_url: https://github.com/{{ name }}/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - pariterre
