{% set name = "bioviz" %}
{% set version = "2.1.8" %}
{% set build_num = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 29e56731d738663a9161379dd1f971a259d015b9f266f3c02b83da61f72147a8

build:
  number: {{ build_num }}
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  string: py{{ py }}_h{{ PKG_HASH }}_{{ build_num }}

requirements:
  host:
    - python
    - pip
  run:
    - python
    - eigen
    - rbdl
    - biorbd
    - casadi
    - rbdl
    - biorbd
    - vtk
    - pyqt
    - pyomeca
    - packaging

test:
  imports:
    - biorbd  # [linux]
    - bioviz  # [not linux]

about:
  home: http://github.com/pyomeca/bioviz
  license: Apache-2.0
  license_file: LICENSE
  summary: Visualization toolkit for the biorbd suite
  description: |
    Biorbd visualization toolkit 
  doc_url: https://github.com/{{ name }}/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - pariterre
